import torch



CONST_K_BANDS = 19
CONST_C_BANDS = 5
CONST_C_PIXELS = 5
CONST_K_PIXELS = 19

TYPE_OF_HDD = "UNDEFINED"

TOL = 1e-6
ALPHA = 0.5
N_NEIGHBORS = 1
TEST_SIZE = 0.2
APPLY_2_NORM =True
dist_dtype = torch.float64 #for resolution adjustments
POOL_SIZE_WASSERSTEIN = 8
POOL_SIZE_HDD = 3
POOL_SIZE_CPU = 8

METRIC_BANDS = 'euclidean'
METRIC_PIXELS = 'euclidean'

REGULAR_METHOD = 0
MEAN_PATCH = 1
MEAN_DISTANCES = 2
WASSERSTEIN = 3

HIERARCHICAL_METHOD = 'HDD'